# Generated by Django 5.1.3 on 2024-11-21 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_limit', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('public_name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.CharField(max_length=500, null=True)),
                ('ticket_price', models.FloatField(null=True)),
                ('raffle_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrizeRaffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prize')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raffle')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('buyer_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('status', models.BooleanField(default=False)),
                ('sale_date', models.DateTimeField(null=True)),
                ('total_paid', models.FloatField(default=0.0)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raffle')),
            ],
        ),
    ]
