# Generated by Django 5.1.3 on 2024-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ganador',
            field=models.BooleanField(default=False),
        ),
    ]
