# Generated by Django 4.2.16 on 2024-11-19 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_ticket_ganador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.AddField(
            model_name='objeto',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='imagen',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='nombrePublico',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='precioTickets',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='celular',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='correo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='nombreComprador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagen',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sorteo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
