# Generated by Django 5.1.3 on 2024-11-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prizeraffle_sorted_prizeraffle_winnerticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
