# Generated by Django 4.2.16 on 2024-11-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ticket_precio_remove_ticket_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='fechaSorteo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fechaVenta',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.objeto')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sorteo')),
            ],
        ),
    ]
