# Generated by Django 4.2.16 on 2024-11-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_status_ticket_is_active_ticket_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
