# Generated by Django 4.2.16 on 2024-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
