# Generated by Django 4.2.16 on 2024-11-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sorteo_fechasorteo_ticket_fechaventa_premio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='premio',
            name='objecto',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='sorteo',
        ),
        migrations.AddField(
            model_name='premio',
            name='descripcion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='imagen',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Objeto',
        ),
        migrations.AddField(
            model_name='premiosorteo',
            name='objecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.premio'),
        ),
        migrations.AddField(
            model_name='premiosorteo',
            name='sorteo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sorteo'),
        ),
    ]
