# Generated by Django 5.1.3 on 2024-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_premiosorteo_remove_premio_objecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='totalPagado',
            field=models.FloatField(default=0.0),
        ),
    ]
