# Generated by Django 4.2.16 on 2024-11-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_totalpagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiosorteo',
            old_name='objecto',
            new_name='premio',
        ),
    ]
