# Generated by Django 4.2.16 on 2024-11-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_raffle_public_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_winner',
        ),
    ]
