# Generated by Django 4.2.16 on 2024-11-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_ticket_is_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='raffleNumber',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(null=True),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('raffle', 'ticketNumber'), name='unique_ticket_per_raffle'),
        ),
    ]
